---
title: "data dictionary"
author: "Jin Kweon"
date: "10/4/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For more information, please refer to "https://www.fifaindex.com/."
```{r}
soccer <- read.csv("/Users/yjkweon24/Desktop/Cal/2017 Fall/PB HLTH 245/Project/Possible data sets/soccer/FullData.csv", header = T)

name <- c()
cat <- c()
description <- c()


dic <- data.frame(
  name <- colnames(soccer), 
  cat <- c("categorical", "categorical", "categorical", "continuous", "categorical", "categorical",
           "continuous", "continuous", "continuous", "continuous", "continuous", "continuous",
           "categorical", "continuous", "continuous", "categorical", "categorical", "categorical",
           "continuous", "continuous", "continuous", "continuous", "continuous", "continuous",
           "continuous", "continuous", "continuous", "continuous", "continuous", "continuous",
           "continuous", "continuous", "continuous", "continuous", "continuous", "continuous",
           "continuous", "continuous", "continuous", "continuous", "continuous", "continuous",
           "continuous", "continuous", "continuous", "continuous", "continuous", "continuous",
           "continuous", "continuous", "continuous", "continuous", "continuous"
           ),
  description <- c("player's name", "player's nationality",
"Empty for retired or not playing this year.
CAM: center attacking midfielder.
CB: center back.
CDM: center defensive midfielder.
CM: center midfielder.
GK: goalkeepr.
LAM: left attacking midfielder. 
LB: left back.
LCB: left center back.
LCM: left center midfielder. 
LDM: left defensive midfielder.
LF: left forward. 
LM: left midfielder.
LS: left stricker.
LW: left wing midfielder/forward.
LWB: left wing back. 
RAM: right attacking midfielder.
RB: right back.
RCB: right center back.
RCM: right center midfielder.
RDM: rifght defensive midfielder.
RF: right forward.
RM: right midfielder.
RS: right stricker.
RW: right wing midfielder/forward. 
RWB: right wing back.
ST: stricker.
Sub: substitution", 
                   "national kit number", 
                   "club players belong to",
                   "club positions (it might be different with national position)",
                   "club kit number",
                   "when players join the current club with date, month, and year",
                   "contract expiration year",
                   "current rating at Fifa17",
                   "players' heights in cm",
                   "players' weights in kg",
                   "players' preferred foot",
                   "players' birth date",
                   "players' ages",
                   "players' preferred positions (it might be different with their positions)",
                   "players' general work rate for each game (High, Med, Low)",
                   "how bad their weak foot is from 1 to 5 (1 is bad)",
                   "how skillful the players are from 1 to 5",
                   "how good the players are at controlling ball from 1 to 100",
                   "how good the players are at dribbling ball from 1 to 100",
                   "how good the players are at marking/defensing oppononents from 1 to 100",
                   "how good the players are at sliding tackle opponents from 1 to 100",
                   "how good the players are at standing tackel opponents from 1 to 100",
                   "how players defense with auto tackles with good strength from 1 to 100",
                   "how fast players react with the ball from 1 to 100",
                   "how players position and move wisely from 1 to 100",
                   "how players intercept ball from oponents from 1 to 100",
                   "how wide players' visions are from 1 to 100",
                   "how stable players are with lots of pressures from 1 to 100",
                   "how players are good at crossing to their teammates from 1 to 100",
                   "how players are good at passing to nearby teammates from 1 to 100",
                   "how players are good at passing to far-away teammates from 1 to 100",
                   "how good players are at acceleration from 1 to 100",
                   "how usually fast players are from 1 to 100",
                   "players' stamina from 1 to 100",
                   "players' strength when players fight for a ball from 1 to 100",
                   "how good players balance without falling down or losing the ball from 1 to 100",
                   "how quick their instant movement is from 1 to 100",
                   "how good at jumping from 1 to 100",
                   "how good at heading from 1 to 100",
                   "how powerful players can shoot from 1 to 100",
                   "how good at scoring when players shoot from 1 to 100",
                   "how good at shooting with far distance from 1 to 100",
                   "how good at curving the ball when shooting from 1 to 100",
                   "how accurate players can shoot for freekick from 1 to 100",
                   "how successful players are for penalty shot from 1 to 100",
                   "how good at volley shot from 1 to 100",
                   "how good at positioning for GK from 1 to 100",
                   "how good at diving for GK from 1 to 100",
                   "how good at kicking/passing for GK from 1 to 100",
                   "how good at handling the ball for GK from 1 to 100",
                   "how fast they can react for GK from 1 to 100"
                   )
  )
colnames(dic) <- c("name", "type", "description")

write.csv(dic, file = "/Users/yjkweon24/Desktop/Cal/2017 Fall/PB HLTH 245/Project/dictionary.csv")
```
